version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdt_webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    restart: unless-stopped