name: Deploy Web API to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH vào EC2 và Deploy code mới
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "== whoami =="
            whoami
            echo "== id =="
            id
            echo "== HOME =="
            echo $HOME
            echo "== PATH =="
            echo $PATH
            echo "== which docker =="
            which docker
            echo "== docker compose version =="
            docker compose version
            echo "== ls cli-plugins =="
            ls -la ~/.docker/cli-plugins 2>&1
            echo "== bat dau deploy =="
            cd ~/tmdt_web_project
            git pull origin main
            docker compose up -d --build